env:
    DEVICE_CODENAME: topaz # Enter your device codename
    ROMREPO: https://github.com/LineageOS/android.git -b lineage-20.0 # Enter ROM repo link
    LOCALMANIFEST: https://github.com/xordinaryme/local_manifest -b main # Enter local_manifest link
    MAKEFILENAME: lineage_topaz # Enter makefile name (example: aosp_fleur)
    VARIANT: eng # Enter build variant (eng, user, userdebug)
    EXTRACMD: # If you want to run any extra command before build
    TARGET: m bacon # Enter target (example: m bacon, make bacon, mka bacon)
    PIXELDRAIN_API_KEY: "ENCRYPTED[!f17e10a6ac1a6fd506ba2a033331495efcd4a360f135610e9224272252ca9c757c98ffba3e6b43bf95e73b7bf12c8e86!]"

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Setup_script:
      - ./scripts/setup.sh || source scripts/setup.sh

  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh

  Requirements_script:
      - ./scripts/device_requirements.sh || source scripts/device_requirements.sh

  Build_script:
      - ./scripts/build.sh || source scripts/build.sh

  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
