env:
    DEVICE_CODENAME: topaz # Enter your device codename
    ROMREPO: https://github.com/PixelExperience/manifest.git -b thirteen-plus # Enter ROM repo link
    LOCALMANIFEST: https://github.com/xordinaryme/local_manifest.git -b main # Enter local_manifest link
    MAKEFILENAME: aosp_topaz # Enter makefile name (example: aosp_fleur)
    VARIANT: eng # Enter build variant (eng, user, userdebug)
    EXTRACMD: # If you want to run any extra command before build
    TARGET: m bacon # Enter target (example: m bacon, make bacon, mka bacon)
    PIXELDRAIN_API_KEY: "ENCRYPTED[!35e35e8aae0cbec39f97949f2bd9e0f7ba7c9698953413c217b1b3cbef847c697cd1a9890f182d6d16a3d9f1eb211d90!]"

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Setup_script:
      - ./scripts/setup.sh || source scripts/setup.sh

  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh

  Requirements_script:
      - ./scripts/device_requirements.sh || source scripts/device_requirements.sh

  Build_script:
      - ./scripts/build.sh || source scripts/build.sh

  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
