env:
    DEVICE_CODENAME: topaz # Enter your device codename
    ROMREPO: https://github.com/PixelOS-AOSP/manifest.git -b thirteen # Enter ROM repo link
    LOCALMANIFEST: https://github.com/xordinaryme/local_manifest.git -b 64 # Enter local_manifest link
    MAKEFILENAME: aosp_topaz # Enter makefile name (example: aosp_fleur)
    VARIANT: userdebug # Enter build variant (eng, user, userdebug)
    EXTRACMD: # If you want to run any extra command before build
    TARGET: m bacon # Enter target (example: m bacon, make bacon, mka bacon)
    PIXELDRAIN_API_KEY: "ENCRYPTED[e5efcf15cfc42f5f5728245b2db391e0d87f0da6fa2f44862dfb9b2b63bb1785cdad933cf040a6a11fa6d68fb85524c3]"
    GOFILE_API_KEY: "ENCRYPTED[bb12ded9ca6e363eb90a8721e8445135d5308ab7e1b7bb847e58aa5db4614e81c4c09e773888e192307862861cf48075]"

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Setup_script:
      - ./scripts/setup.sh || source scripts/setup.sh

  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh

  Requirements_script:
      - ./scripts/device_requirements.sh || source scripts/device_requirements.sh

  Build_script:
      - ./scripts/build.sh || source scripts/build.sh

  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
