env:
    DEVICE_CODENAME: topaz # Enter your device codename
    ROMREPO: https://github.com/LineageOS/android.git -b lineage-20.0 # Enter ROM repo link
    LOCALMANIFEST: https://github.com/belowzeroiq/local_manifest.git -b 64 # Enter local_manifest link
    MAKEFILENAME: lineage_topaz # Enter makefile name (example: aosp_fleur)
    VARIANT: userdebug # Enter build variant (eng, user, userdebug)
    EXTRACMD: # If you want to run any extra command before build
    TARGET: mka bacon # Enter target (example: m bacon, make bacon, mka bacon)
    PIXELDRAIN_API_KEY: "ENCRYPTED[46234771d0bb012179618b4e3596a65fa5acd491e804700b1c83c174787342df57ce64aa093f12156c8c43776d15cb45]"

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Setup_script:
      - ./scripts/setup.sh || source scripts/setup.sh

  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh

  Requirements_script:
      - ./scripts/device_requirements.sh || source scripts/device_requirements.sh

  Build_script:
      - ./scripts/build.sh || source scripts/build.sh

  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
