env:
    DEVICE_CODENAME: tapas # Enter your device codename
    ROMREPO: # Enter ROM repo link
    LOCALMANIFEST: https://github.com/xordinaryme/local_manifest -b main # Enter local_manifest link
    MAKEFILENAME: aosp_tapas # Enter makefile name (example: aosp_fleur)
    VARIANT: user # Enter build variant (eng, user, userdebug)
    EXTRACMD: # If you want to run any extra command before build
    TARGET: mka bacon # Enter target (example: m bacon, make bacon, mka bacon)
    PIXELDRAIN_API_KEY: "ENCRYPTED[!b8e1a7c7324e2ac746b2e0de6e3f76a2daad3590015d58d83cdf650eb8703ecd05f360b374354209f96f91519428bee0!]"

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Setup_script:
      - ./scripts/setup.sh || source scripts/setup.sh

  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh

  Requirements_script:
      - ./scripts/device_requirements.sh || source scripts/device_requirements.sh

  Build_script:
      - ./scripts/build.sh || source scripts/build.sh

  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
