env:
    DEVICE: fleur #Enter your device codename
    ROMREPO: https://github.com/SuperiorOS/manifest.git -b thirteen #Enter roms's repo link
    LOCALMANIFEST: https://github.com/RT1648/local_manifest-fleurprebuilt.git #Enter device local_manifest link & make sure all the neccessary repos are available in your localmanifest
    MAKEFILENAME: superior_fleur #Enter makefile name example-aosp_fleur,etc...
    VARIENT: userdebug #Enter build varient among these - eng,user & userdebug
    TARGET: mka bacon #Enter target example- m bacon, make bacon , mka bacon,etc...
    F: ci:ci #Your Gdrive Folder Path which u have set in rclone
    E: ENCRYPTED[9ae7cbda659d9e2f3f3f38f26aaa820c87faa6f573bf73493f30395da502340c34b652d0140459e5c310ea6b015a415d] #Encrypted id which u obtained from cirrusci after encrypting your rclone values
    LINK: https://sourceforge.net/projects/fleur/files/ccache/Superior/ccache.tar.gz/download #Enter ccache link if u already have for any rom, if u dont have one, put ### in the field

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Setup_script:
      - ./scripts/setup.sh || source scripts/setup.sh
  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh
  Build_script:
      - ./scripts/build.sh || source scripts/build.sh
  Upload_script:
      - ./scripts/upload.sh || source scripts/setup.sh
